version: '3.9'

services:
  flibusta-bot:
    build:
      context: .
    working_dir: /home/node/app
    depends_on:
      - pocketbase
    network_mode: "container:gluetun"
    restart: always

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    network_mode: "container:gluetun"
    volumes:
      - /path/to/data:/pb_data
    healthcheck: #optional (recommended) since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

